import { registerNamespace } from '@/i18n';

/** Ikkala sahifa (ro'yxat va jadval) bitta nom maydonidan foydalanadi */
registerNamespace('batches', {
  uz: {
    title: 'Partiyalar',
    subtitle: 'Xitoydan olingan tovarlar tannarxi — har bir partiya alohida jadvalda',
    new: 'Yangi partiya',
    defaultName: '{n}-partiya',
    'create.name': 'Nomi',
    'create.rate': 'Kurs: 1 ¥ necha so‘m',
    'create.rateHint': 'Markaziy bank kursi · {date}',
    'create.rateFallback': 'Taxminiy kurs — Markaziy bankka ulanib bo‘lmadi',
    'create.submit': 'Yaratish',
    'col.name': 'Partiya',
    'col.items': 'Tovarlar',
    'col.cny': 'Jami (¥)',
    'col.goods': 'Tovarlar (so‘m)',
    'col.cargo': 'Cargo (so‘m)',
    'col.total': 'Umumiy (so‘m)',
    items: '{n} ta',
    'empty.title': 'Hali partiya yo‘q',
    'empty.hint': 'Birinchi partiyani yarating — tovarlar, trek kodlar va kargo haqini bitta jadvalda yuriting.',
    'delete.title': 'Partiyani o‘chirish',
    'delete.text': '«{name}» va undagi {n} ta qator butunlay o‘chiriladi.',
    deleted: 'Partiya o‘chirildi',
    'error.create': 'Partiya yaratilmadi',
    'error.delete': 'Partiya o‘chirilmadi',
    // Jadval
    back: 'Barcha partiyalar',
    'f.name': 'Partiya nomi',
    'f.rate': 'Kurs: 1 ¥ =',
    'f.extra': 'Qo‘shimcha xarajat',
    'f.extraHint': 'bojxona, qadoq, yo‘l haqi va h.k.',
    'rate.cbu': 'MB kursi',
    'rate.cbuHint': 'Markaziy bankning bugungi kursini qo‘yish',
    sum: 'so‘m',
    'kpi.cny': 'Jami narxi (¥)',
    'kpi.goods': 'Tovarlar (so‘m)',
    'kpi.cargo': 'Cargo (so‘m)',
    'kpi.extra': 'Qo‘shimcha',
    'kpi.total': 'Umumiy (so‘m)',
    'kpi.goodsHint': '{cny} ¥ × {rate}',
    'kpi.cargoHint': 'Avia {avia} · Avto {avto}',
    'kpi.totalHint': '{n} ta tovar',
    'kpi.totalHintQty': '{n} ta tovar · {qty} dona',
    'kpi.cargoHintKg': 'Avia {avia} · Avto {avto} · {kg} kg',
    'th.no': '№',
    'th.name': 'Nomi',
    'th.track': 'Trek kod',
    'th.cny': 'Narxi (¥)',
    'th.uzs': 'Narxi (so‘m)',
    'th.cargoName': 'Cargo nomi',
    'th.delivery': 'Yetkazish',
    'th.cargo': 'Cargo (so‘m)',
    'th.total': 'Umumiy (so‘m)',
    'th.qty': 'Soni',
    'th.kg': 'Kg',
    'th.unit': '1 dona (so‘m)',
    'th.unitHint': 'Umumiy ÷ Soni — tovar va cargo bilan 1 donaning tannarxi (qo‘shimcha xarajat kirmaydi)',
    'th.cnyHint': 'Shu qatordagi barcha donalar uchun to‘langan narx',
    'delivery.avia': 'Avia',
    'delivery.avto': 'Avto',
    'cargo.pick': 'Tanlang',
    'cargo.new': '+ Yangi cargo…',
    'cargo.newTitle': 'Yangi cargo',
    'cargo.newHint': 'Keyingi qatorlarda va boshqa partiyalarda ham ro‘yxatdan tanlanadi',
    'cargo.add': 'Qo‘shish',
    'ph.name': 'Tovar nomi',
    'ph.track': 'Trek kod',
    'row.add': 'Qator qo‘shish',
    'row.delete': 'Qatorni o‘chirish',
    'rows.limit': 'Bitta partiyada ko‘pi bilan {n} ta qator bo‘ladi',
    total: 'Jami',
    tip: 'Sariq kataklarni o‘zingiz to‘ldirasiz, qolgani avtomatik hisoblanadi. Enter — pastki katak, oxirgi qatorda yangi qator. Hammasi o‘zi saqlanadi.',
    'save.pending': 'O‘zgarishlar bor',
    'save.saving': 'Saqlanmoqda…',
    'save.saved': 'Saqlandi',
    'save.error': 'Saqlanmadi',
    'save.retry': 'Qayta urinish',
    readonly: 'Sizda faqat ko‘rish huquqi bor',
    notFound: 'Partiya topilmadi',
  },
  ru: {
    title: 'Партии',
    subtitle: 'Себестоимость товаров из Китая — каждая партия в отдельной таблице',
    new: 'Новая партия',
    defaultName: 'Партия {n}',
    'create.name': 'Название',
    'create.rate': 'Курс: 1 ¥ в сумах',
    'create.rateHint': 'Курс Центробанка · {date}',
    'create.rateFallback': 'Примерный курс — Центробанк недоступен',
    'create.submit': 'Создать',
    'col.name': 'Партия',
    'col.items': 'Товары',
    'col.cny': 'Итого (¥)',
    'col.goods': 'Товары (сум)',
    'col.cargo': 'Карго (сум)',
    'col.total': 'Всего (сум)',
    items: '{n} шт.',
    'empty.title': 'Партий пока нет',
    'empty.hint': 'Создайте первую партию — товары, трек-коды и карго в одной таблице.',
    'delete.title': 'Удалить партию',
    'delete.text': '«{name}» и все её строки ({n}) будут удалены безвозвратно.',
    deleted: 'Партия удалена',
    'error.create': 'Не удалось создать партию',
    'error.delete': 'Не удалось удалить партию',
    back: 'Все партии',
    'f.name': 'Название партии',
    'f.rate': 'Курс: 1 ¥ =',
    'f.extra': 'Доп. расходы',
    'f.extraHint': 'таможня, упаковка, дорога и т.п.',
    'rate.cbu': 'Курс ЦБ',
    'rate.cbuHint': 'Подставить сегодняшний курс Центробанка',
    sum: 'сум',
    'kpi.cny': 'Итого цена (¥)',
    'kpi.goods': 'Товары (сум)',
    'kpi.cargo': 'Карго (сум)',
    'kpi.extra': 'Доп. расходы',
    'kpi.total': 'Всего (сум)',
    'kpi.goodsHint': '{cny} ¥ × {rate}',
    'kpi.cargoHint': 'Авиа {avia} · Авто {avto}',
    'kpi.totalHint': 'Товаров: {n}',
    'kpi.totalHintQty': 'Товаров: {n} · {qty} шт.',
    'kpi.cargoHintKg': 'Авиа {avia} · Авто {avto} · {kg} кг',
    'th.no': '№',
    'th.name': 'Название',
    'th.track': 'Трек-код',
    'th.cny': 'Цена (¥)',
    'th.uzs': 'Цена (сум)',
    'th.cargoName': 'Карго',
    'th.delivery': 'Доставка',
    'th.cargo': 'Карго (сум)',
    'th.total': 'Всего (сум)',
    'th.qty': 'Кол-во',
    'th.kg': 'Кг',
    'th.unit': '1 шт (сум)',
    'th.unitHint': 'Всего ÷ Кол-во — себестоимость 1 шт с карго (доп. расходы не входят)',
    'th.cnyHint': 'Сумма, уплаченная за все штуки в строке',
    'delivery.avia': 'Авиа',
    'delivery.avto': 'Авто',
    'cargo.pick': 'Выберите',
    'cargo.new': '+ Новое карго…',
    'cargo.newTitle': 'Новое карго',
    'cargo.newHint': 'Потом его можно выбрать в других строках и партиях',
    'cargo.add': 'Добавить',
    'ph.name': 'Название товара',
    'ph.track': 'Трек-код',
    'row.add': 'Добавить строку',
    'row.delete': 'Удалить строку',
    'rows.limit': 'В одной партии не больше {n} строк',
    total: 'Итого',
    tip: 'Жёлтые ячейки заполняете вы, остальное считается само. Enter — ячейка ниже, на последней строке — новая строка. Всё сохраняется автоматически.',
    'save.pending': 'Есть изменения',
    'save.saving': 'Сохранение…',
    'save.saved': 'Сохранено',
    'save.error': 'Не сохранено',
    'save.retry': 'Повторить',
    readonly: 'У вас доступ только на просмотр',
    notFound: 'Партия не найдена',
  },
  en: {
    title: 'Batches',
    subtitle: 'Landed cost of goods from China — one table per batch',
    new: 'New batch',
    defaultName: 'Batch {n}',
    'create.name': 'Name',
    'create.rate': 'Rate: 1 ¥ in UZS',
    'create.rateHint': 'Central Bank rate · {date}',
    'create.rateFallback': 'Approximate rate — Central Bank unreachable',
    'create.submit': 'Create',
    'col.name': 'Batch',
    'col.items': 'Items',
    'col.cny': 'Total (¥)',
    'col.goods': 'Goods (UZS)',
    'col.cargo': 'Cargo (UZS)',
    'col.total': 'Total (UZS)',
    items: '{n}',
    'empty.title': 'No batches yet',
    'empty.hint': 'Create your first batch — goods, tracking codes and cargo fees in one table.',
    'delete.title': 'Delete batch',
    'delete.text': '“{name}” and its {n} rows will be deleted permanently.',
    deleted: 'Batch deleted',
    'error.create': 'Could not create the batch',
    'error.delete': 'Could not delete the batch',
    back: 'All batches',
    'f.name': 'Batch name',
    'f.rate': 'Rate: 1 ¥ =',
    'f.extra': 'Extra costs',
    'f.extraHint': 'customs, packaging, transport etc.',
    'rate.cbu': 'CBU rate',
    'rate.cbuHint': 'Use today’s Central Bank rate',
    sum: 'UZS',
    'kpi.cny': 'Total price (¥)',
    'kpi.goods': 'Goods (UZS)',
    'kpi.cargo': 'Cargo (UZS)',
    'kpi.extra': 'Extra',
    'kpi.total': 'Total (UZS)',
    'kpi.goodsHint': '{cny} ¥ × {rate}',
    'kpi.cargoHint': 'Air {avia} · Road {avto}',
    'kpi.totalHint': '{n} items',
    'kpi.totalHintQty': '{n} items · {qty} pcs',
    'kpi.cargoHintKg': 'Air {avia} · Road {avto} · {kg} kg',
    'th.no': '#',
    'th.name': 'Name',
    'th.track': 'Tracking code',
    'th.cny': 'Price (¥)',
    'th.uzs': 'Price (UZS)',
    'th.cargoName': 'Cargo',
    'th.delivery': 'Delivery',
    'th.cargo': 'Cargo (UZS)',
    'th.total': 'Total (UZS)',
    'th.qty': 'Qty',
    'th.kg': 'Kg',
    'th.unit': 'Per unit (UZS)',
    'th.unitHint': 'Total ÷ Qty — landed cost of one unit incl. cargo (extra costs not included)',
    'th.cnyHint': 'Amount paid for all units in the row',
    'delivery.avia': 'Air',
    'delivery.avto': 'Road',
    'cargo.pick': 'Select',
    'cargo.new': '+ New cargo…',
    'cargo.newTitle': 'New cargo',
    'cargo.newHint': 'You can pick it later in other rows and batches',
    'cargo.add': 'Add',
    'ph.name': 'Product name',
    'ph.track': 'Tracking code',
    'row.add': 'Add row',
    'row.delete': 'Delete row',
    'rows.limit': 'A batch can hold up to {n} rows',
    total: 'Total',
    tip: 'You fill in the yellow cells, the rest is calculated. Enter moves down; on the last row it adds a new one. Everything saves automatically.',
    'save.pending': 'Unsaved changes',
    'save.saving': 'Saving…',
    'save.saved': 'Saved',
    'save.error': 'Not saved',
    'save.retry': 'Retry',
    readonly: 'You have view-only access',
    notFound: 'Batch not found',
  },
});

/**
 * "1 786,62", "1786.62", "1,786.62" — hammasini raqamga aylantiradi.
 * `integer` — so'mdagi summa: "8,000" va "8.000" sakkiz ming bo'ladi, sakkiz emas.
 * Tushunib bo'lmaydigan matn ("1761.321786.62") uchun NaN — chaqiruvchi eski
 * qiymatni saqlab qoladi, uni jimgina 0 ga aylantirmaydi.
 */
export function parseAmount(value: string, integer = false): number {
  let s = value.replace(/[\s  ]/g, '');
  if (integer) return Number(s.replace(/[^\d]/g, ''));
  // Ikkala belgi bo'lsa — oxirgisi kasr ajratkichi, qolgani minglik
  const lastDot = s.lastIndexOf('.');
  const lastComma = s.lastIndexOf(',');
  if (lastDot >= 0 && lastComma >= 0) {
    const dec = lastDot > lastComma ? '.' : ',';
    s = s.split(dec === '.' ? ',' : '.').join('').replace(dec, '.');
  } else {
    s = s.replace(',', '.');
  }
  return Number(s.replace(/[^\d.]/g, ''));
}
